### ISSUE TITLE
Python2 backward compatibility

### ISSUE THREAD

**Issue by leventyalcin** [drewsonne/pyum#1]
Hi, 

As you may know, there is no distro which comes with Python 3 yet. I'd like to keep the OS simple as much as I can and don't like to install software if it's not really a reuirement. Especially if a cli tool needs it. 

I've tried to use yum2s3 on CentOS 6 which comes with Python 2.7 and it thrown an expection about  importing `urllib` which is `urlparse` and `http.client` which is `httplib` in Python2.

https://github.com/drewsonne/pyum/commit/ca78decb72bcd4b9ec50fa34cd45965b36381e17#commitcomment-15340831

Thanks,

**Comment by drewsonne** [comment]
That's a fair point. This project has fallen behind a little bit, so I'll warn you, the whole thing doesn't work yet, as I'm still getting my head around the rpm dependency chain and how to resolve it between packages.

**Comment by drewsonne** [comment]
I did a bit of work last night, and got the test cases running for python 2.7.
