### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [drewsonne/pyum#11]
@drewsonne I think your code is great... I am considering using it as a library in https://github.com/nexB/scancode-toolkit which is overall Apache-licensed. I was wondering if you would consider using a license that would be amenable to a library usage such as the LGPL, Apache, BSD, GPL with linking exception, etc?

Thank you for your kind consideration. Ignore this if you feel strongly about using only the GPL.

**Comment by drewsonne** [comment]
I generally don't have particularly strong feelings about OSS licences except that if you modify **my** code, I want you to have to release the modifications you made. _ie_, if you make improvements to **my** code, then I want everyone else to share in that.

After having a bit of a read, about the whole derivative works thing, I think I'd be happy to re-license this as LGPL, as I don't think I need to have a right to make someone else open source their code/use the same licence, if they don't modify my work.

Is the LGPL ok for your needs?

That said... if it ever becomes a problem, then pyum has become far more prevalent than I ever anticipated, and that's probably a good thing. ;-)

**Comment by pombredanne** [comment]
Thank you for the quick reply!
I am perfectly fine with LGPL or a GPL with linking exception: both would work well with Apache. And this is all for reuse in a FLOSS project in any case. I also always contribute back fixes and improvements "upstream".

**Comment by pombredanne** [comment]
and funnily enough what scancode https://github.com/nexB/scancode-toolkit does is to detect licenses (and packages). There you use the pyrpm fork from @02strich, I maintain for now my own fork of the original code from @mjvm in https://github.com/nexB/scancode-toolkit/tree/develop/src/packagedcode/pyrpm  but I will need eventually to send this back to @mjvm that restarted commit a bit or join forces :)

**Comment by pombredanne** [comment]
Actually the LGPL would work great as there is one codebase that I have been lurking at https://github.com/kholia/pyrpm/tree/ng maintained/forked by @kholia  which is yet another `pyrpm` (or the original) which is essentially under the LGPL-2.0 https://github.com/kholia/pyrpm/blob/8f327db47aaddc9303b3335a72b668a2dbd5aa99/pyrpm/config.py#L2

So LGPL-2.0 would make reusing code from there quite easy IMHO. In particular for adding things such as reading yum sqlite DB for instance which would be very nice...

**Comment by drewsonne** [comment]
I've addressed this in my latest commit. Using the LGPL licence.

I got stuck at figuring out RPM dependencies, but I might have a shot at that again soon.

**Comment by pombredanne** [comment]
@drewsonne Thank you ++!
